In [1]:
import numpy  as np 
import pandas as pd

In [2]:
df=pd.read_csv(r'E:\NLP\imdb movie review dataset\test_data (1).csv\IMDB Dataset.csv\IMDB Dataset.csv')

In [3]:
df.head()

                                              review sentiment
0  One of the other reviewers has mentioned that ...  positive
1  A wonderful little production. <br /><br />The...  positive
2  I thought this was a wonderful way to spend ti...  positive
3  Basically there's a family where a little boy ...  negative
4  Petter Mattei's "Love in the Time of Money" is...  positive

In [4]:
df['review'][1]

'A wonderful little production. <br /><br />The filming technique is very unassuming- very old-time-BBC fashion and gives a comforting, and sometimes discomforting, sense of realism to the entire piece. <br /><br />The actors are extremely well chosen- Michael Sheen not only "has got all the polari" but he has all the voices down pat too! You can truly see the seamless editing guided by the references to Williams\' diary entries, not only is it well worth the watching but it is a terrificly written and performed piece. A masterful production about one of the great master\'s of comedy and his life. <br /><br />The realism really comes home with the little things: the fantasy of the guard which, rather than use the traditional \'dream\' techniques remains solid then disappears. It plays on our knowledge and our senses, particularly with the scenes concerning Orton and Halliwell and the sets (particularly of their flat with Halliwell\'s murals decorating every surface) are terribly well done.'

In [8]:
df.isnull().sum()

review       0
sentiment    0
dtype: int64

In [7]:
df['sentiment'].value_counts()

sentiment
positive    25000
negative    25000
Name: count, dtype: int64

In [9]:
df.duplicated().sum()

np.int64(418)

In [10]:
df.drop_duplicates(inplace=True)

In [12]:
df.duplicated().sum()

np.int64(0)

1.basic preprocessing
2.remove tags 
3.lowercasee remove stopwords

In [13]:
import re
def remove_tag(text):
    cleaned_text=re.sub(re.compile('<.*?>'),'',text)
    return cleaned_text

In [15]:
df['review']=df['review'].apply(remove_tag)

In [16]:
df['review'][1]

'A wonderful little production. The filming technique is very unassuming- very old-time-BBC fashion and gives a comforting, and sometimes discomforting, sense of realism to the entire piece. The actors are extremely well chosen- Michael Sheen not only "has got all the polari" but he has all the voices down pat too! You can truly see the seamless editing guided by the references to Williams\' diary entries, not only is it well worth the watching but it is a terrificly written and performed piece. A masterful production about one of the great master\'s of comedy and his life. The realism really comes home with the little things: the fantasy of the guard which, rather than use the traditional \'dream\' techniques remains solid then disappears. It plays on our knowledge and our senses, particularly with the scenes concerning Orton and Halliwell and the sets (particularly of their flat with Halliwell\'s murals decorating every surface) are terribly well done.'

In [18]:
df['review'] = df['review'].str.lower()

In [20]:
from nltk.corpus import stopwords
sw_list=stopwords.words('english')
df['review']=df['review'].apply(lambda x:[item for item in x.split() if item not in sw_list]).apply(lambda x: " ".join(x))

In [21]:
from nltk.corpus import stopwords

sw_list = set(stopwords.words('english'))

clean_reviews = []

for review in df['review']:
    words = review.split()
    filtered = []

    for word in words:
        if word not in sw_list:
            filtered.append(word)

    clean_reviews.append(" ".join(filtered))

df['review'] = clean_reviews

In [22]:
df

                                                  review sentiment
0      one reviewers mentioned watching 1 oz episode ...  positive
1      wonderful little production. filming technique...  positive
2      thought wonderful way spend time hot summer we...  positive
3      basically there's family little boy (jake) thi...  negative
4      petter mattei's "love time money" visually stu...  positive
...                                                  ...       ...
49995  thought movie right good job. creative origina...  positive
49996  bad plot, bad dialogue, bad acting, idiotic di...  negative
49997  catholic taught parochial elementary schools n...  negative
49998  going disagree previous comment side maltin on...  negative
49999  one expects star trek movies high art, fans ex...  negative

[49582 rows x 2 columns]

In [24]:
x=df.iloc[:,0:1]
y=df['sentiment']

In [26]:
y ## we need to do the label encoding

0        positive
1        positive
2        positive
3        negative
4        positive
           ...
49995    positive
49996    negative
49997    negative
49998    negative
49999    negative
Name: sentiment, Length: 49582, dtype: object

In [27]:
from sklearn.preprocessing import LabelEncoder
encoder=LabelEncoder()
y=encoder.fit_transform(y)

In [28]:
y

array([1, 1, 1, ..., 0, 0, 0], shape=(49582,))

In [29]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test= train_test_split(x,y,test_size=0.3,random_state=1)

In [31]:
x_train.shape

(34707, 1)

In [ ]:
#applying bow
from sklearn.feature_extraction.text import CountVectorizer
cv=CountVectorizer()

In [ ]:
cv = CountVectorizer()
x_train_bow = cv.fit_transform(x_train['review']).toarray()
x_test_bow = cv.transform(x_test['review']).toarray()
x_test_bow=cv.fit_transform(x_test['review']).toarray()

NameError: name 'cv' is not defined